[package]
name = "zxgraph"
version = "0.1.0"
edition = "2021"

[lib]
name = "zxgraph"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
petgraph = { version = "0.8", features = ["stable_graph"] }
fraction = "0.15.3"
thiserror = "2.0.17"